version: 2
updates:
  - package-ecosystem: gradle
    directory: "/http4k-app"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"      
  - package-ecosystem: gradle
    directory: "/ktor-app"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"      
# - package-ecosystem: gradle
#   directory: "/micronaut-app"
#   schedule:
#     interval: "weekly"
  - package-ecosystem: gradle
    directory: "/quarkus-app"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"      
  - package-ecosystem: gradle
    directory: "/springboot-app"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"      
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
