quarkus:
  datasource:
    db-kind: "postgresql"
    username: "myuser"
    password: "mypassword"
    jdbc:
      url: "jdbc:postgresql://localhost:5432/mydb"
      max-size: 20
    reactive:
      url: "postgresql://localhost:5432/mydb"
      max-size: 20
  vault:
    url: "http://localhost:8200"
    authentication:
      client-token: "mytoken"
