spring:
  cloud:
    vault:
      enabled: true
      uri: "http://${VAULT_HOST:localhost}:8200"
      authentication: "TOKEN"
      token: "mytoken"
      kv:
        enabled: true
        backend: "secret"
        default-context: "myapp"
        application-name: "myapp"
  config:
    import: optional:vault://
  datasource:
    url: "jdbc:postgresql://${database.host}:${database.port}/${database.name}"
    username: "${database.username}"
    password: "${database.password}"
    driver-class-name: "org.postgresql.Driver"
  flyway:
    enabled: true

database:
  host: "${DB_HOST:localhost}"
  port: 5432
  name: "mydb"
  username: "myuser"
  password: "mypassword"

greeting:
  name: "Bitelchus"
