name: Http4k

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/http4k.yml
      - docker-compose.yaml
      - http4k-app/**
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/http4k.yml
      - docker-compose.yaml
      - http4k-app/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6
      with:
        arguments: build
        build-root-directory: http4k-app
