name: Http4k

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/http4k
      - docker-compose.yaml
      - http4k-app/**
  pull_request:
    branches: [ "main" ]
    paths:
      - http4k-app/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a
      with:
        arguments: build
        build-root-directory: http4k-app
