name: Ktor

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/ktor.yml
      - docker-compose.yaml
      - ktor-app/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/ktor.yml
      - docker-compose.yaml
      - ktor-app/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build
        working-directory: ktor-app
        run: ./gradlew build
