name: Quarkus

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/quarkus
      - docker-compose.yaml
      - quarkus-app/**
  pull_request:
    branches: [ "main" ]
    paths:
      - quarkus-app/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: quarkus-app
