name: Quarkus

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/quarkus.yml
      - docker-compose.yaml
      - quarkus-app/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/quarkus.yml
      - docker-compose.yaml
      - quarkus-app/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build
        working-directory: quarkus-app
        run: ./gradlew build
